### ISSUE TITLE
It may make sense to upstream your specs into https://github.com/kaitai-io/kaitai_struct_formats/

### ISSUE THREAD

**Issue by KOLANICH** [Game3DEE/adoom#3]

**Comment by Ithamar** [comment]
That is my intent once I figure out the last missing piece for character animations. Until then, this repository should be pretty easy to find if you are looking for kaitai specs for Darkstone, I would think ;)

**Comment by Ithamar** [comment]
Yeah, I have a large bunch of specs around for a variety of game engines. adoom/darkstone are examples of where I'm trying to bring them to a point where they are reasonably complete (or at least complete enough to be useful).

For both I'm still fighting with the character animation formats, which I'm close to having figured out, just need some time to finish them.

Once they are (reasonably) complete and tested, I'll push them up to kaitai-struct-formats, like I've done with my renderware format mods.
